services: 
  db:
    image: postgres:15
    container_name: medi-system-db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=postgres
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - medi-system-db:/var/lib/postgresql/data
    networks:
      - medi-system-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: medi-system-pgadmin
    restart: always
    ports:
      - "5050:80" 
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    networks:
      - medi-system-network

volumes:
  medi-system-db:

networks:
  medi-system-network:
    driver: bridge

