services:
  db:
    image: postgres:15
    container_name: db-workflows-ia
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=postgres
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-workflows-ia:/var/lib/postgresql/data
    networks: [workflows-ia-network]

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-workflows
    restart: always
    ports: ["5050:80"]
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on: [db]
    networks: [workflows-ia-network]

  files-service:
    build:
      context: ./files-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8082
    depends_on: [db]
    ports: ["8082:8082"]
    networks: [workflows-ia-network]


  patients-service:
    build:
      context: ./patients-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8081
    depends_on: [db]
    ports: ["8081:8081"]
    networks: [workflows-ia-network]

  gateway-service:
    build:
      context: ./gateway-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_CONFIG_IMPORT_CHECK_ENABLED: "false"
    depends_on: [files-service, patients-service]
    ports: ["8080:8080"]
    networks: [workflows-ia-network]

volumes:
  db-workflows-ia:

networks:
  workflows-ia-network:
    driver: bridge

